services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: edu-rise-dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app # Connect local folder to container
      - /app/node_modules # Protect internal container node_modules
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
